# Generated by Django 4.1.7 on 2023-03-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('diets', models.CharField(max_length=255)),
                ('cuisine', models.CharField(max_length=255)),
                ('ingredients', models.JSONField()),
                ('serving', models.PositiveIntegerField()),
                ('steps', models.JSONField()),
                ('prep_time', models.PositiveIntegerField(blank=True, null=True)),
                ('cooking_time', models.PositiveIntegerField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('comment', models.JSONField(default=dict)),
                ('creator', models.CharField(max_length=255)),
                ('base_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
