# Generated by Django 4.1.7 on 2023-03-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_creator_alter_step_cooking_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='image',
        ),
        migrations.RemoveField(
            model_name='step',
            name='recipe',
        ),
        migrations.AddField(
            model_name='step',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_photos/'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(to='recipes.step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='cooking_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='prep_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='recipe_videos/'),
        ),
    ]
