# Generated by Django 4.1.7 on 2023-04-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_photo_recipe_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='rate',
            new_name='rating',
        ),
    ]
