# Generated by Django 4.1.7 on 2023-04-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_rate_recipe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='num_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
