# Generated by Django 4.1.7 on 2023-04-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='num_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_mark',
            field=models.JSONField(default=dict),
        ),
    ]
