# Generated by Django 4.1.7 on 2023-04-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_num_mark_recipe_total_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='comment',
        ),
        migrations.AddField(
            model_name='recipe',
            name='comment',
            field=models.ManyToManyField(to='recipes.comment'),
        ),
    ]
