# Generated by Django 4.1.7 on 2023-04-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_comment_remove_recipe_comment_recipe_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.comment'),
        ),
    ]
