# Generated by Django 4.1.7 on 2023-04-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentator',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
